name: SwiftComponentPlayground
options:
  bundleIdPrefix: com.dtoebe
  deploymentTarget:
    iOS: "18.1"
    macOS: "15.0"
targets:
  SwiftComponentPlayground:
    type: application
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "18.1"
      macOS: "15.0"
    sources:
      - path: Sources/SwiftComponentPlayground
        excludes:
          - "Info.plist"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.dtoebe.SwiftComponentPlayground
      SWIFT_VERSION: "6.2"
      DEVELOPMENT_TEAM: "EMBMMC3VGP"
      CODE_SIGN_STYLE: Automatic
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
      # ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES

info:
  properties:
    CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
    CFBundleExecutable: $(EXECUTABLE_NAME)
    CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
    CFBundleName: $(PRODUCT_NAME)
    CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    CFBundleShortVersionString: "1.0"
    CFBundleVersion: "1"
    UIApplicationSceneManifest:
      UIApplicationSupportsMultipleScenes: true
    UILaunchScreen: {}

schemes:
  SwiftComponentPlayground-iOS:
    build:
      targets:
        SwiftComponentPlayground_iOS: all
    run:
      config: Debug
    test:
      config: Debug

  SwiftComponentPlayground-macOS:
    build:
      targets:
        SwiftComponentPlayground_macOS: all
    run:
      config: Debug
    test:
      config: Debug
